### ISSUE TITLE
Windows 10 URUCC+1.2 patch

### ISSUE THREAD

**Issue by Kitsune-Ultima** [Jrius/Drizzle#1]
On Windows 10 with URU Complete Chronicles with the 1.2 patch results in this error.
`Error: You appear to be running Windows Vista or Windows Seven.  Uru has a bug that will require a workaround, see http://myst.dustbird.net/wiki/Drizzle#Vista_and_above for details.`

**Comment by Jrius** [comment]
Wow, sorry for not answering sooner. Yeah, this message is accurate: Uru sometimes has issues if it's installed in Program Files and you're running it from a non-admin account. It doesn't always happen, but that's something to look out for.

**Comment by Kitsune-Ultima** [comment]
ah ok thanks!
